### ISSUE TITLE
有类似 wsdump.py 的实现吗？

### ISSUE THREAD

**Issue by XhinLiang** [asyncins/asyncwsc#1]

**Comment by XhinLiang** [comment]
https://github.com/websocket-client/websocket-client/blob/master/bin/wsdump.py

**Comment by asyncins** [comment]
> https://github.com/websocket-client/websocket-client/blob/master/bin/wsdump.py

你好，XhinLiang。请你描述这段代码的功能作用以及应用场景，以便我更好的理解和解答

**Comment by XhinLiang** [comment]
wsdump.py 是一个简单的命令行 REPL 客户端，用于连接 websocket 服务器。
所有的输入都会原封不动地发给服务器。
服务器的所有响应都会写到命令行中。

**Comment by asyncins** [comment]
> wsdump.py 是一个简单的命令行 REPL 客户端，用于连接 websocket 服务器。
> 所有的输入都会原封不动地发给服务器。
> 服务器的所有响应都会写到命令行中。

这个需求理解了。目前没有实现这个功能的计划。不过如果需要的话，你可以在代码中实现，使用 Python 中的 input 将命令行中输入的内容通过 send 方法发送给服务端。
